### PR TITLE
Add ability to find and parse compilation database

### PR DESCRIPTION
**Pull request by rwols**
Well, basic functionality is there. I'll have to do a little more tests.

### CODE REVIEW

**Comment by pieterverstraete** [comment]
Looks very nice! I haven't been able to set this up on my working environment yet, will try to do this tomorrow.

**Comment by rwols** [comment]
Thanks! I'm wondering if in the case of headers, we should first check if that header is in the comp db, but this will work for now.

**Comment by pieterverstraete** [comment]
You mean when we are adding an include line inside a header file? What would be the advantage of first looking in the comp db?

**Comment by rwols** [comment]
I've stumbled upon [this project](https://github.com/Sarcasm/compdb) which is supposed to take an existing `compile_commands.json` (generated from CMake for instance) and then also generate compile commands for header files. I'm not sure how precise that would be (what should the compilation commands be for an arbitrary header?), but it's something to keep in mind that maybe there's actually an item for a header file in the compdb.

**Pull request merged**
